### ISSUE TITLE
designate location for derived data for the UK Biobank from pre-processing activities

### ISSUE THREAD

**Issue by bryancaron** [neurohub/neurohub_datasets#1]
Action item:
We need to designate the location within the NeuroHub UK Biobank directory tree for the derived data:

We have tractoflow data that needs to go somewhere official, and most of the squashFS files have already been produced but are currently sitting in a user sub-directory of the allocation.

**Comment by bryancaron** [comment]
Hi Darcy, 

Can you please designate a location for where the derived data can go within the UK Biobank tree?  Thanks.

Bryan.

**Comment by dlq** [comment]
I've updated the [UK Biobank File System Layout](https://docs.google.com/document/d/1aL5t5WixfkTl81oq7xZkGPXmKr8KYpL07wzThLbOAMk/edit?usp=sharing) to include with a `Derived` directory that includes new data that is possibly also in `Restructured` and to be returned to UK Biobank.

**Comment by dlq** [comment]
I have made the directory `/lustre03/project/6008063/neurohub/ukbb/Derived` on `beluga`.

**Comment by jbpoline** [comment]
Thanks Darcy - note that BIDS has a specification for [derived data](https://bids-specification.readthedocs.io/en/stable/05-derivatives/01-introduction.html) so if these are bids-derived eg with BIDS apps we may want to simlink (eg have something in the BIDS dir to point to the derivatives)
