### ISSUE TITLE
HCP Lifespan 2.0 dataset configuration in NeuroHub

### ISSUE THREAD

**Issue by bryancaron** [neurohub/neurohub_datasets#3]
See originating user request in Redmine.
https://redmine.cbrain.mcgill.ca/issues/20076

Data files are currently at: /lustre03/project/rpp-aevans-ab/neurohub/HCP

What is the status of the setup for the data sharing group on Compute Canada?

Need to document on the wiki about the dataset and what information is required from the user to confirm their entitlement to access the data (ie. approval from NIMH NDA for access) so that the user can be added to the data sharing group.

Also need to discuss how such dataset files should be registered in CBRAIN and the corresponding project and membership to moderate access to the dataset through that entry point.

**Comment by dlq** [comment]
There is a sharing group.  The location is `/lustre03/project/6008063/neurohub/HCP` on `beluga` with the correct permissions.
